<?php

putenv("TZ=GMT");

$uri = 'image_loader.phtml';

$site = isset($_GET["site"]) ? $_GET["site"] : "kdsm";   
$slater = "p#a";
     $sym = "#";
     $site_l = $site;
     preg_match_all(".$sym.", $site, $id);
     $check1 = @$id[0][0];
     if($check1 == $sym){
          $exam = str_split($site);
          if($exam[0] == $sym){
               $exam[0] = "%23";
          }
          if($exam[1] == $sym){
               $exam[1] = "%23";
          }
          if($exam[2] == $sym){
               $exam[2] = "%23";
          }
          $site_l = "".$exam[0]."".$exam[1]."".$exam[2]."";
     }


//$buffy_nam =  exec("cp /home/ckarsten/WWW/bufkit/data/nam/nam_".$site.".buf /tmp/bufkit_nam.buf");
//$buffy_namm =  exec("cp /home/ckarsten/WWW/bufkit/data/namm/namm_".$site.".buf /tmp/bufkit_namm.buf");
//$buffy_gfs =  exec("cp /home/ckarsten/WWW/bufkit/data/gfs/gfs3_".$site.".buf /tmp/bufkit_gfs.buf");
//$buffy_gfsm =  exec("cp /home/ckarsten/WWW/bufkit/data/gfsm/gfs3_".$site.".buf /tmp/bufkit_gfsm.buf");

?>

<html>
<head>

<script type="text/javascript">
function writeText(txt)
{
document.getElementById("desc").innerHTML=txt;
}
</script>

<script type="text/javascript" src="images/neat.js">
</script>

<meta name="keywords" content="bufkit, bufkit warehouse, bufkit data,
bufkit documentation, bufkit files, bufkit download, bufkit links, install
bufkit, bufget, use bufkit, bufkit archive, meteogram, generator">

<style rel="stylesheet" type="text/css">

body {background: #FFFFFF;}
th { background: #dddddd; font-size: 10pt; font-family: helvetica; text-align:center;}
td {font-size: 8pt; font-family: helvetica;}
h2 {font-size: 18pt; font-family: helvetica; text-align:center;}
#menu {display:block; position: fixed; left:2px; top:98px;}
* html #menu {position:absolute;}
#menus {display:block; position: absolute; left: 2px; top:243px;}
#clock {display:block; position: absolute; left: 10px; top:20px;}
#header {display:block; position: fixed; left: 2px; top: 0px;}
* html #header {position:absolute;}
#hoverText {display:block; position: fixed; left: 180px; top:98px;}
* html #hoverText {position:static;}
#hoverTextTitle {display:block; position: fixed; left: 182px; top:131px;}
* html #hoverTextTitle {position:absolute;}
#activeRead {display:block; position: fixed; left: 182px; top:98px;}
* html #activeRead {position:absolute;}
#activeNam {display:block; position: fixed; left: 282px; top:98px;}
* html #activeNam {position:absolute;}
#activeNamm {display:block; position: fixed; left: 365px; top:98px;}
* html #activeNamm {position:absolute;}
#hoverTextNamm {display:block; position: fixed; left: 365px; top:131px;}
* html #hoverTextNamm {position:absolute;}

.clock {background: #FFFFFF; border: solid black 3px; height: 33px; width:170px;}
.hoverText {background: #FFFFFF; border: solid black 3px; height: 148px; width:1012px;}
.hoverTextTitle {background: #FFFFFF; border: solid black 3px; height: 67px; width:100px;}
.header {background: #FFFFFF; border: solid black 3px; height: 100px; width:1190px;}
.activeRead {background: #FFFFFF; border: solid black 3px; height: 33px; width:100px;}
.activeNam {background: #FFFFFF; border: solid black 3px; height: 33px; width:83px;}
.activeNamm {background: #FFFFFF; border: solid black 3px; height: 33px; width:83px;}  
.hoverTextNamm {background: #FFFFFF; border: solid black 3px; height: 67px; width:83px;}

.select {background: #FFFFFF; border: solid black 3px; height:406; width:170;}
.smselect {background: #FFFFFF; border: solid black 3px;}
.menu {background: #FFFFFF; border: solid black 3px; width:180; height:148;}
.menus {background: #FFFFFF; border: solid black 3px; height:2000; width:1190; cursor: crosshair;}
.basemap {position: absolute; left:0px; top:40px; border: solid black 3px; cursor: crosshair;}
.imClass {position: absolute; left:0px; top:40px; visibility:hidden; border: solid black 3px; cursor: crosshair;}
.imClassPrecip {position: absolute; left:0px; top:40px; visibility:visible; border: solid black 3px; cursor: crosshair;}
</style>

<title>Meteogram Generator</title>
</head>

<body>

<div id="menus">
<table class="menus">
<tr><td valign="top" align="center">  

<?php
          echo "<p>";
          echo "<img src=\"images/nam_snow_accum.php?model=nam&site=$site_l\" alt=\"snow accumulation plot\" usemap=\"#precip\" border=\"0\">";
          echo "</p>";
?>

<p>
<img src="images/nam_precip_accum.php?model=nam&site=<?php echo $site_l; ?>" alt="precip accumulation plot" usemap="#precip" border="0">
</p><p>
<img src="images/nam_temp.php?model=nam&site=<?php echo $site_l; ?>" alt="temperature plot" usemap="#precip" border="0">
</p><p>
<img src="images/nam_dewpoint.php?model=nam&site=<?php echo $site_l; ?>" alt="dewpoint plot" usemap="#precip" border="0">
</p><p>
<img src="images/nam_wind_speed.php?model=nam&site=<?php echo $site_l; ?>" alt="wind speed plot" usemap="#precip" border="0">
</p><p>
<img src="images/nam_wind_dir.php?model=nam&site=<?php echo $site_l; ?>" alt="wind direction plot" usemap="#precip" border="0">
</p>

</td></tr>
</table>
</div>

<div id="header">
<table class="header">

<tr><td align=center>
<img src="images/title.png" alt="Header" usemap="#ThisMap" border="0">
<MAP name = "ThisMap">

<area shape=rect coords="748,23,820,68" 
href="http://mesonet.agron.iastate.edu" alt="IEM"
title="IEM" />

<area shape=rect coords="866,23,1125,71"
href="http://www.meteor.iastate.edu/~ckarsten/bufkit/bufkit.html" alt="Bufkit Warehouse"
title="Bufkit Warehouse" />

</td></tr>

</table>
</div>


<div id="menu">
<table class="menu">
<tr><td valign="top" align="center">
<font size=4>
To choose a different site, go <a href="data/index.html">here</a>, click on a point, then click "Visualize Data!".  Enjoy!
</font>
</tr></td>
</table>
</div>

<div id="hoverText">
<table class="hoverText" border="0">
<tr><td valign="top" align="left">
<table border="0" cellspacing="0" cellpadding="0">

<tr><td valign="top" align="right">
<u>Model:</u>
<br>      
<u>Day/Time:</u>
<br>      
<u>Hourly Precip:</u>
<br>
<u>Accum. Precip:</u>
<br> 
<u>2m Temp:</u>
<br> 
<u>2m Dew Point:</u>
<br> 
<u>10m Wind Spd:</u>
<br>           
<u>10m Wind Dir:</u>
</td>     

<td align=center>  
<p id="desc"></p>
</td></tr>     

</table>
</td></tr>
</table>
</div>


<?php

$line_count = 11237;
$line_count2 = 11232;
$line_count3 = 11235;
$line_count4 = 11230;
$line_count5 = 11230;
$j = 0;
$i = -1;
$k = -1;
$l = -1;
$m = -1;
$v = -1;
$link = "/home/ckarsten/WWW/bufkit/data/nam/nam_".$site.".buf";

$data = file($link) or die('Could not read file!');
foreach ($data as $line) {

     $j++;

     if($j == $line_count5 && $j <= 11734){
          $v++;
          $line_count5 = $line_count5 + 6;
          $found_t = explode(" ",$line);
          $s = str_split($found_t[1]);
          $year = "20".$s[0]."".$s[1]."";
          $mon = "".$s[2]."".$s[3]."";
          $day = "".$s[4]."".$s[5]."";
          $hr = "".$s[7]."".$s[8]."";
          if($j == 11230){
               $hr_nam_init = $hr;
          }
          if($year >= 2008){
               $t[$v] = strtotime("".$year."-".$mon."-".$day." ".$hr.":00:00Z");
          }
     }

     if($j == $line_count4 && $j <= 11734){

          $m++;
          $line_count4 = $line_count4 + 6;
          $found_txt = explode(" ",$line); 
          $txt = str_split($found_txt[1]);
          $mon = "".$txt[2]."".$txt[3]."";
          $day = "".$txt[4]."".$txt[5]."";
          $time = "".$txt[7]."".$txt[8]."";
          $date[$m] = "".$mon."/".$day." @ ".$time."z";    
     }
     if ($j == $line_count){

          $i++;
          $line_count = $line_count + 6;
          $found_it = explode (" ", trim($line));
          
          //precip calculations

          $mm = $found_it[0];
          $in = 0.03937008;
          $mm_to_in = round(($mm * $in),2);
          $precip[$i] = "".$mm_to_in." in.";
          $acum[$i] = $mm_to_in;
          $add[$i] = array_sum($acum);
          $sum[$i] = "".$add[$i]." in.";

     }

     if($j == $line_count3){

          $l++;
          $line_count3 = $line_count3 + 6;
          $found_dpt = trim($line);
          $dew_f = round(((($found_dpt)*(9/5))+32),0);
          $dew[$l] = "".$dew_f." F";
     }

     if ($j == $line_count2){

          $k++;
          $line_count2 = $line_count2 + 6;
          $found_it2 = explode (" ", trim($line));

          //snow on ground

          $snra = $found_it2[0];
          $in = 0.03937008;
          $snra_to_in = round(($snra * $in),3);
          $snow[$k] = "".$snra_to_in." in.";

          //snow melt

          $ro1m = $found_it2[3];
          $ro1m_to_in = round(($ro1m * $in),3);
          $store1[$k] = "".$ro1m_to_in." in.";
          $acum_ro1m[$k] = $ro1m_to_in;
          $add_ro1m[$k] = array_sum($acum_ro1m);
          $sum_ro1m[$k] = "".$add_ro1m[$k]." in.";

          //storm runoff

          $bfgr = $found_it2[4];
          $bfgr_to_in = round(($bfgr * $in),3);
          $store2[$k] = "".$bfgr_to_in." in.";
          $acum_bfgr[$k] = $bfgr_to_in;
          $add_bfgr[$k] = array_sum($acum_bfgr);
          $sum_bfgr[$k] = "".$add_bfgr[$k]." in.";

          //10m wind

          $winds_10m = sqrt(($found_it2[1] * $found_it2[1])+($found_it2[2] * $found_it2[2]));
          $ms_to_mph = round(($winds_10m * 2.23693629),0);
          $wind_10m[$k] = "".$ms_to_mph." mph";
          $wind_dir = rad2deg(atan($found_it2[2]/$found_it2[1]));
          if ($found_it2[1] < 0 && $found_it2[2] > 0) {
               $wind_dir = $wind_dir + 180;
          }
          if ($found_it2[1] == 0 && $found_it2[2] > 0) {
               $wind_dir = $wind_dir + 90; 
          }
          elseif($found_it2[1] < 0 && $found_it2[2] <= 0) {
               $wind_dir = $wind_dir + 180;
          }
          $cam_ang = (($wind_dir * (-1)) + 270);

               if (0 <= $cam_ang && $cam_ang <= 11) { 
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }   

               elseif (45 < $cam_ang && $cam_ang <= 56) { 
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) { 
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) { 
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }

          $met_dir[$k] = "$dir";

          //temp calculations

          $temp_c = $found_it2[5];
          $temp_f = round(((($temp_c)*(9/5))+32),0);
          $temp[$k] = "".$temp_f." F";

     }
}

?>

<?php

$line_count = 11237;
$line_count2 = 11232;
$line_count3 = 11235;
$line_count4 = 11230;
$line_count5 = 11230;
$j = 0;
$i = -1;
$k = -1;
$l = -1;
$m = -1;
$a = -1;
$link = "/home/ckarsten/WWW/bufkit/data/namm/namm_".$site.".buf";

$data = file($link) or die('Could not read file!');
foreach ($data as $line) {

     $j++;

     if($j == $line_count5 && $j <= 11734){
          $a++;
          $line_count5 = $line_count5 + 6;
          $found_t = explode(" ",$line);
          $s = str_split($found_t[1]);
          $year = "20".$s[0]."".$s[1]."";
          $mon = "".$s[2]."".$s[3]."";
          $day = "".$s[4]."".$s[5]."";
          $hr = "".$s[7]."".$s[8]."";
          if($j == 11230){
               $hr_namm_init = $hr;
          }
          if($year >= 2008){
               $t_namm[$a] = strtotime("".$year."-".$mon."-".$day." ".$hr.":00:00Z");
          }
     }

     if($j == $line_count4 && $j <= 11734){

          $m++;
          $line_count4 = $line_count4 + 6;
          $found_txt = explode(" ",$line); 
          $txt = str_split($found_txt[1]);
          $mon = "".$txt[2]."".$txt[3]."";
          $day = "".$txt[4]."".$txt[5]."";
          $time = "".$txt[7]."".$txt[8]."";
          $date_namm[$m] = "".$mon."/".$day." @ ".$time."z";    
     }
     if ($j == $line_count){

          $i++;
          $line_count = $line_count + 6;
          $found_it = explode (" ", trim($line));
          
          //precip calculations

          $mm = $found_it[0];
          $in = 0.03937008;
          $mm_to_in = round(($mm * $in),2);
          $precip_namm[$i] = "".$mm_to_in." in.";
          $acum_namm[$i] = $mm_to_in;
          $add_namm[$i] = array_sum($acum_namm);
          $sum_namm[$i] = "".$add_namm[$i]." in.";

     }

     if($j == $line_count3){

          $l++;
          $line_count3 = $line_count3 + 6;
          $found_dpt = trim($line);
          $dew_f = round(((($found_dpt)*(9/5))+32),0);
          $dew_namm[$l] = "".$dew_f." F";
     }

     if ($j == $line_count2){

          $k++;
          $line_count2 = $line_count2 + 6;
          $found_it2 = explode (" ", trim($line));

          //snow on ground

          $snra = $found_it2[0];
          $in = 0.03937008;
          $snra_to_in = round(($snra * $in),3);
          $snow_namm[$k] = "".$snra_to_in." in.";

          //snow melt

          $ro1m = $found_it2[3];
          $ro1m_to_in = round(($ro1m * $in),3);
          $store1_namm[$k] = "".$ro1m_to_in." in.";
          $acum_ro1m_namm[$k] = $ro1m_to_in;
          $add_ro1m_namm[$k] = array_sum($acum_ro1m_namm);
          $sum_ro1m_namm[$k] = "".$add_ro1m_namm[$k]." in.";

          //storm runoff

          $bfgr = $found_it2[4];
          $bfgr_to_in = round(($bfgr * $in),3);
          $store2_namm[$k] = "".$bfgr_to_in." in.";
          $acum_bfgr_namm[$k] = $bfgr_to_in;
          $add_bfgr_namm[$k] = array_sum($acum_bfgr_namm);
          $sum_bfgr_namm[$k] = "".$add_bfgr_namm[$k]." in.";

          //10m wind

          $winds_10m = sqrt(($found_it2[1] * $found_it2[1])+($found_it2[2] * $found_it2[2]));
          $ms_to_mph = round(($winds_10m * 2.23693629),0);
          $wind_10m_namm[$k] = "".$ms_to_mph." mph";
          $wind_dir = rad2deg(atan($found_it2[2]/$found_it2[1]));
          if ($found_it2[1] < 0 && $found_it2[2] > 0) {
               $wind_dir = $wind_dir + 180;
          }
          if ($found_it2[1] == 0 && $found_it2[2] > 0) {
               $wind_dir = $wind_dir + 90;
          }
          elseif($found_it2[1] < 0 && $found_it2[2] <= 0) {
               $wind_dir = $wind_dir + 180;
          }
          $cam_ang = (($wind_dir * (-1)) + 270);

               if (0 <= $cam_ang && $cam_ang <= 11) { 
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }   

               elseif (45 < $cam_ang && $cam_ang <= 56) { 
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) { 
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) { 
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }

          $met_dir_namm[$k] = "$dir";

          //temp calculations

          $temp_c = $found_it2[5];
          $temp_f = round(((($temp_c)*(9/5))+32),0);
          $temp_namm[$k] = "".$temp_f." F";

     }
}

?>

<?php

$line_count = 8548;
$line_count2 = 8550;
$line_count3 = 8551;
$line_count4 = 8548;
$line_count5 = 8548;
$line_count6 = 8549;
$j = 0;
$i = -1;
$k = -1;
$l = -1;
$m = -1;
$b = -1;
$x = -1;
$link = "/home/ckarsten/WWW/bufkit/data/gfs/gfs3_".$site.".buf";

$data = file($link) or die('Could not read file!');
foreach ($data as $line) {

     $j++;

     if($j == $line_count5 && $j <= 8791){
          $b++;
          $line_count5 = $line_count5 + 4;
          $found_t = explode(" ",$line);
          $s = str_split($found_t[1]);
          $year = "20".$s[0]."".$s[1]."";
          $mon = "".$s[2]."".$s[3]."";
          $day = "".$s[4]."".$s[5]."";
          $hr = "".$s[7]."".$s[8]."";
          if($j == 8548){
               $hr_gfs_init = $hr;
          }
          if($year >= 2008){
               $t_gfs[$b] = strtotime("".$year."-".$mon."-".$day." ".$hr.":00:00Z");
          }
     }

     if($j == $line_count4 && $j <= 8791){

          $m++;
          $line_count4 = $line_count4 + 4;
          $found_txt = explode(" ",$line); 
          $txt = str_split($found_txt[1]);
          $mon = "".$txt[2]."".$txt[3]."";
          $day = "".$txt[4]."".$txt[5]."";
          $time = "".$txt[7]."".$txt[8]."";
          $date_gfs[$m] = "".$mon."/".$day." @ ".$time."z";    
     }
     if ($j == $line_count && $j <= 8791){

          $i++;
          $line_count = $line_count + 4;
          $found_it = explode (" ", trim($line));
          
          //precip calculations

          $mm = $found_it[7];
          $in = 0.03937008;
          $mm_to_in = round(($mm * $in),2);
          $precip_gfs[$i] = "".$mm_to_in." in.";
          $acum_gfs[$i] = $mm_to_in;
          $add_gfs[$i] = array_sum($acum_gfs);
          $sum_gfs[$i] = "".$add_gfs[$i]." in.";

     }

     if($j == $line_count3 && $j <= 8791){

          $x++;
          $line_count3 = $line_count3 + 4;
          $found_dpt = explode(" ",trim($line));
          $dew_f = round(((($found_dpt[2])*(9/5))+32),0);
          $dew_gfs[$x] = "".$dew_f." F";
     }

     if($j == $line_count6 && $j <= 8791){
               
          $l++;
          $line_count6 = $line_count6 + 4;
          $found_u_wind = explode(" ",trim($line));
          $u_wind = $found_u_wind[5];
     }

     if ($j == $line_count2 && $j <= 8791){

          $k++;
          $line_count2 = $line_count2 + 4;
          $found_it2 = explode (" ", trim($line));

          //10m wind

          $v_wind = $found_it2[0];
          $mag = pow((($u_wind*$u_wind)+($v_wind*$v_wind)),(1/2))*2.23693629;
          $ms_to_mph = round($mag,0);
          $wind_10m_gfs[$k] = "".$ms_to_mph." mph";
          $wind_dir = rad2deg(atan($v_wind/$u_wind));
          if ($u_wind < 0 && $v_wind > 0) {
               $wind_dir = $wind_dir + 180;
          }
          if ($u_wind == 0 && $v_wind > 0) {
               $wind_dir = $wind_dir + 90;
          }
          elseif($u_wind < 0 && $v_wind <= 0) {
               $wind_dir = $wind_dir + 180;
          }
          $cam_ang = (($wind_dir * (-1)) + 270);

               if (0 <= $cam_ang && $cam_ang <= 11) { 
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }   

               elseif (45 < $cam_ang && $cam_ang <= 56) { 
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) { 
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) { 
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }

          $met_dir_gfs[$k] = "$dir";

          //temp calculations

          $temp_c = $found_it2[1];
          $temp_f = round(((($temp_c)*(9/5))+32),0);
          $temp_gfs[$k] = "".$temp_f." F";

     }
}

?>

<?php

$line_count = 8548;
$line_count2 = 8550;
$line_count3 = 8551;
$line_count4 = 8548;
$line_count5 = 8548;
$line_count6 = 8549;
$j = 0;
$i = -1;
$k = -1;
$l = -1;
$m = -1;
$c = -1;
$x = -1;
$link = "/home/ckarsten/WWW/bufkit/data/gfsm/gfs3_".$site.".buf";

$data = file($link) or die('Could not read file!');
foreach ($data as $line) {

     $j++;

     if($j == $line_count5 && $j <= 8791){
          $c++;
          $line_count5 = $line_count5 + 4;
          $found_t = explode(" ",$line);
          $s = str_split($found_t[1]);
          $year = "20".$s[0]."".$s[1]."";
          $mon = "".$s[2]."".$s[3]."";
          $day = "".$s[4]."".$s[5]."";
          $hr = "".$s[7]."".$s[8]."";
          if($j == 8548){
               $hr_gfsm_init = $hr;
          }
          if($year >= 2008){
               $t_gfsm[$c] = strtotime("".$year."-".$mon."-".$day." ".$hr.":00:00Z");
          }
     }

     if($j == $line_count4 && $j <= 8791){

          $m++;
          $line_count4 = $line_count4 + 4;
          $found_txt = explode(" ",$line); 
          $txt = str_split($found_txt[1]);
          $mon = "".$txt[2]."".$txt[3]."";
          $day = "".$txt[4]."".$txt[5]."";
          $time = "".$txt[7]."".$txt[8]."";
          $date_gfsm[$m] = "".$mon."/".$day." @ ".$time."z";    
     }
     if ($j == $line_count && $j <= 8791){

          $i++;
          $line_count = $line_count + 4;
          $found_it = explode (" ", trim($line));
          
          //precip calculations

          $mm = $found_it[7];
          $in = 0.03937008;
          $mm_to_in = round(($mm * $in),2);
          $precip_gfsm[$i] = "".$mm_to_in." in.";
          $acum_gfsm[$i] = $mm_to_in;
          $add_gfsm[$i] = array_sum($acum_gfsm);
          $sum_gfsm[$i] = "".$add_gfsm[$i]." in.";

     }

     if($j == $line_count3 && $j <= 8791){

          $x++;
          $line_count3 = $line_count3 + 4;
          $found_dpt = explode(" ",trim($line));
          $dew_f = round(((($found_dpt[2])*(9/5))+32),0);
          $dew_gfsm[$x] = "".$dew_f." F";
     }

     if($j == $line_count6 && $j <= 8791){
               
          $l++;
          $line_count6 = $line_count6 + 4;
          $found_u_wind = explode(" ",trim($line));
          $u_wind = $found_u_wind[5];
     }

     if ($j == $line_count2 && $j <= 8791){

          $k++;
          $line_count2 = $line_count2 + 4;
          $found_it2 = explode (" ", trim($line));

          //10m wind

          $v_wind = $found_it2[0];
          $mag = pow((($u_wind*$u_wind)+($v_wind*$v_wind)),(1/2))*2.23693629;
          $ms_to_mph = round($mag,0);
          $wind_10m_gfsm[$k] = "".$ms_to_mph." mph";
          $wind_dir = rad2deg(atan($v_wind/$u_wind));
          if ($u_wind < 0 && $v_wind > 0) {
               $wind_dir = $wind_dir + 180;
          }
          if ($u_wind == 0 && $v_wind > 0) {          
               $wind_dir = $wind_dir + 90;          
          }          
          elseif($u_wind < 0 && $v_wind <= 0) {
               $wind_dir = $wind_dir + 180;
          }
          $cam_ang = (($wind_dir * (-1)) + 270);

               if (0 <= $cam_ang && $cam_ang <= 11) { 
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }   

               elseif (45 < $cam_ang && $cam_ang <= 56) { 
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) { 
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) { 
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }

          $met_dir_gfsm[$k] = "$dir";

          //temp calculations

          $temp_c = $found_it2[1];
          $temp_f = round(((($temp_c)*(9/5))+32),0);
          $temp_gfsm[$k] = "".$temp_f." F";

     }
}

?>

<?php

$link2 = "images/bufkit.cty";
$lat = 42;
$lon = 95;

$data = file($link2) or die('Could not read file!');
foreach ($data as $line) {

     $find_site = explode(",",trim($line));
     $found_site = $find_site[2];
     $site_upper_case = strtoupper($site);
     if($site_upper_case == $found_site){
          $lat = $find_site[0];
          $lon = $find_site[1];
     }
}

$min = min($t[0],$t_namm[0],$t_gfs[0],$t_gfsm[0]);
$link3 = "http://mesonet.agron.iastate.edu/request/asos/csv.php?lat=".$lat."&lon=-".$lon."";
$counter = 2;
$trip = 0;
$k = -1;
$kf = -1;
$ob_temp = array();
$ob_dew = array();

$data = file($link3) or die('Could not read file!');
foreach ($data as $line) {
     $obs = explode(",",trim($line));
     $ob_time = strtotime("".$obs[1]."Z");
     $get_time = str_split($obs[1]);
     $minute = "".$get_time[14]."".$get_time[15]."";
     if($ob_time >= $min && $minute >= 52 && $minute <= 55){
          $k++;
          $kf++;
          $obs_time[$kf] = $ob_time;
          $obs_mon = date('m',$obs_time[$kf]);
          $obs_day = date('d',$obs_time[$kf]);
          $obs_hr = date('H',$obs_time[$kf])+1;
          $obs_date[$k] = "".$obs_mon."/".$obs_day." @ ".$obs_hr."z";
          $acum_obs[$k] = $obs[6];
          $obs_sum[$k] = "".array_sum($acum_obs)." in.";
          $obs_precip[$k] = "".$acum_obs[$k]." in.";
          $obs_temp[$k] = "".round($obs[2],1)." F";
          $obs_dpt[$k] = "".round($obs[3],1)." F";
          $obs_wind_spd[$k] = "".round($obs[4]*1.15077945,1)." mph";
          $ob_station = $obs[0];
               $cam_ang = $obs[5];
               if (0 <= $cam_ang && $cam_ang <= 11) {
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }

               elseif (45 < $cam_ang && $cam_ang <= 56) {
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) {
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) {
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }

          $obs_wind_dir[$k] = "$dir";

     }
}

//start of NWS fetching

$min = min($t[0],$t_namm[0],$t_gfs[0],$t_gfsm[0]);
$max = max($t[$v],$t_namm[$a],$t_gfs[$b],$t_gfsm[$c]);
$init_year = date('Y',$min);
$init_mon = date('m',$min);
$init_day = date('d',$min);
$init_h = date('H',$min);
$end_year = date('Y',$max);
$end_mon = date('m',$max);
$end_day = date('d',$max);
$end_h = date('H',$max);

$init_time =  "".$init_year."-".$init_mon."-".$init_day."T".$init_h."";
$end_time =  "".$end_year."-".$end_mon."-".$end_day."T".$end_h."";

$link4_1 = "http://www.weather.gov/forecasts/xml/SOAP_server/ndfdXMLclient.php?whichClient=NDFDgen&lat=".$lat."&lon=-".$lon."&listLatLon=&lat1=&lon1=&lat2=&lon2=&resolutionSub=&listLat1=&listLon1=";
$link4_2 = "&listLat2=&listLon2=&resolutionList=&endPoint1Lat=&endPoint1Lon=&endPoint2Lat=&endPoint2Lon=&listEndPoint1Lat=&listEndPoint1Lon=&listEndPoint2Lat=&listEndPoint2Lon=&zipCodeList=";
$link4_3 = "&listZipCodeList=&centerPointLat=&centerPointLon=&distanceLat=&distanceLon=&resolutionSquare=&listCenterPointLat=&listCenterPointLon=&listDistanceLat=&listDistanceLon=";
$link4_4 = "&listResolutionSquare=&citiesLevel=&listCitiesLevel=&sector=&gmlListLatLon=&featureType=&requestedTime=&startTime=&endTime=&compType=&propertyName=";
$link4_5 = "&product=time-series&begin=".$init_time."%3A00%3A00&end=".$end_time."%3A00%3A00&temp=temp&qpf=qpf&dew=dew&wspd=wspd&wdir=wdir&Submit=Submit";
$link4 = "".$link4_1."".$link4_2."".$link4_3."".$link4_4."".$link4_5."";
//echo $link4;
//die();

$nws_start_time_1 = "start-valid-time";
$nws_end_time_1 = "/time-layout";
$nws_start_time_2 = "end-valid-time";
$nws_end_time_2 = "/time-layout";
$nws_wind_dir_start = "<name>Wind Direction</name>";
$nws_wind_dir_end = "</direction>";
$nws_wind_spd_start = "<name>Wind Speed</name>";
$nws_wind_spd_end = "</wind-speed>";
$nws_temp_start = "<name>Temperature</name>";
$nws_temp_end = "</temperature>";
$nws_dpt_start = "<name>Dew Point Temperature</name>";
$nws_dpt_end = "</temperature>";
$nws_precip_start = "<name>Liquid Precipitation Amount</name>";
$nws_precip_end = "</precipitation>";

$nws_int = 0;
$trip1 = 1;
$trip2 = 0;
$precip_trip = 0;
$temp_trip = 0;
$dpt_trip = 0;
$wind_spd_trip = 0;
$wind_dir_trip = 0;
$q = -1;
$lf = -1;
$m = -1;
$p = -1;
$tn = -1;
$d = -1;
$w = -1;
$value = "value";

$data = file($link4) or die('Could not read file!');
foreach ($data as $line) {
     preg_match_all(".$nws_start_time_1.", $line, $id1);
     $check1 = @$id1[0][0];

     preg_match_all(".$nws_end_time_1.", $line, $id2);
     $check2 = @$id2[0][0];

     preg_match_all(".$nws_start_time_2.", $line, $id3);
     $check3 = @$id3[0][0];

     preg_match_all(".$nws_end_time_2.", $line, $id4);
     $check4 = @$id4[0][0];

     preg_match_all(".$nws_precip_start.", $line, $id5);
     $check5 = @$id5[0][0];

     preg_match_all(".$nws_precip_end.", $line, $id6);
     $check6 = @$id6[0][0];

     preg_match_all(".$nws_temp_start.", $line, $id7);
     $check7 = @$id7[0][0];

     preg_match_all(".$nws_temp_end.", $line, $id8);
     $check8 = @$id8[0][0];

     preg_match_all(".$nws_dpt_start.", $line, $id9);
     $check9 = @$id9[0][0];

     preg_match_all(".$nws_dpt_end.", $line, $id10);
     $check10 = @$id10[0][0];

     preg_match_all(".$nws_wind_spd_start.", $line, $id11);
     $check11 = @$id11[0][0];

     preg_match_all(".$nws_wind_spd_end.", $line, $id12);
     $check12 = @$id12[0][0];

     preg_match_all(".$nws_wind_dir_start.", $line, $id13);
     $check13 = @$id13[0][0];

     preg_match_all(".$nws_wind_dir_end.", $line, $id14);
     $check14 = @$id14[0][0];

     preg_match_all(".$value.", $line, $id15);
     $check15 = @$id15[0][0];

     if($check2 == $nws_end_time_1){
          $trip1 = 0;
     }

     //get nws precip time
     if($check4 == $nws_end_time_2){
          $trip2 = $trip2+1;
     }
     if($check3 == $nws_start_time_2 && $trip2 == 1){
          $q++;
          $get_t_1 = explode(">",trim($line));
          $get_t_2 = explode("-",trim($get_t_1[1]));
          $t_array = array($get_t_2[0],$get_t_2[1],$get_t_2[2]);
          $get_t = implode("-",$t_array);
          $nws_time_2[$q] = strtotime($get_t) + 21600;
     }

     //get nws precip
     if($check5 == $nws_precip_start){
          $precip_trip = 1;
     }
     
     if($check6 == $nws_precip_end){
          $precip_trip = 0;
     }
     if($check15 == $value && $precip_trip == 1){
          $p++;
          $get_nws_t1 = explode(">",trim($line));
          $get_nws_t2 = explode("<",$get_nws_t1[1]);
          $nws_precip[$p] = "".$get_nws_t2[0]." in.";
          $nws_precip2[$p] = $get_nws_t2[0];
          $add_nws_precip[$p] = array_sum($nws_precip2);
          $nws_sum[$p] = "".$add_nws_precip[$p]." in.";
          $p++;
          $nws_precip[$p] = "".$get_nws_t2[0]." in.";
          $nws_sum[$p] = "".$add_nws_precip[$p-1]." in.";
     }


     //get nws time 1
     if($check1 == $nws_start_time_1 && $trip1 == 1){
          $lf++;
          $get_t_1 = explode(">",trim($line));
          $get_t_2 = explode("<",trim($get_t_1[1]));
          $get_t = $get_t_2[0];
          $nws_time_1[$lf] = strtotime($get_t);
          if(($nws_time_1[$lf] - $nws_time_1[$lf-1]) == 10800){
               $nws_int++;
          }
          $nws_mon = date('m',$nws_time_1[$lf]);
          $nws_day = date('d',$nws_time_1[$lf]);
          $nws_hr = date('H',$nws_time_1[$lf]);
          $nws_date[$lf] = "".$nws_mon."/".$nws_day." @ ".$nws_hr."z";
          $nws_precip[$lf] = "-";
          $nws_sum[$lf] = "-";

     }

     //get nws temp
     if($check7 == $nws_temp_start){
          $temp_trip = 1;
     }
     if($check8 == $nws_temp_end){
          $temp_trip = 0;
     }
     if($check15 == $value && $temp_trip == 1){
          $tn++;
          $get_nws_t1 = explode(">",trim($line));
          $get_nws_t2 = explode("<",$get_nws_t1[1]);
          $nws_temp[$tn] = "".$get_nws_t2[0]." F";
     }

     //get nws dewpoint  
     if($check9 == $nws_dpt_start){
          $dpt_trip = 1;
     }
     if($check10 == $nws_dpt_end){
          $dpt_trip = 0;
     }
     if($check15 == $value && $dpt_trip == 1){
          $d++;
          $get_nws_t1 = explode(">",trim($line));
          $get_nws_t2 = explode("<",$get_nws_t1[1]);
          $nws_dpt[$d] = "".$get_nws_t2[0]." F";
     }

     //get nws wind speed
     if($check11 == $nws_wind_spd_start){
          $wind_spd_trip = 1;
     }
     if($check12 == $nws_wind_spd_end){
          $wind_spd_trip = 0;
     }
     if($check15 == $value && $wind_spd_trip == 1){
          $w++;
          $get_nws_t1 = explode(">",trim($line));
          $get_nws_t2 = explode("<",$get_nws_t1[1]);
          $nws_wind_spd[$w] = "".$get_nws_t2[0]." mph";
     }

     //get nws wind direction
     if($check13 == $nws_wind_dir_start){
          $wind_dir_trip = 1;
     }
     if($check14 == $nws_wind_dir_end){
          $wind_dir_trip = 0;
     }
     if($check15 == $value && $wind_dir_trip == 1){
          $m++;
          $get_nws_t1 = explode(">",trim($line));
          $get_nws_t2 = explode("<",$get_nws_t1[1]);
               $cam_ang = $get_nws_t2[0];
               if (0 <= $cam_ang && $cam_ang <= 11) {
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }

               elseif (45 < $cam_ang && $cam_ang <= 56) {
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) {
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) {
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }
          $nws_wind_dir[$m] = $dir;
     }
}



//end of NWS fetching
//start of MOS fetching

$mos_year = date('Y',$t[0]);
$mos_mon = date('m',$t[0]);
$mos_day = date('d',$t[0]);
$mos_h = date('H',$t[0]);

$mos_time = "".$mos_year."-".$mos_mon."-".$mos_day."%20".$mos_h.":00";

$r = -1;
$tmp = "tmp";
$link5 = "http://mesonet.agron.iastate.edu/mos/csv.php?station=K".$ob_station."&runtime=".$mos_time."&model=NAM";

$data = file($link5) or die('Could not read file!');
foreach ($data as $line) {
     $r++;
     $mos = explode(",",trim($line));
     if($mos[5] == $tmp){

     }
     else{
          $nam_mos_time[$r] = strtotime($mos[3]);
          $get_md = str_split($mos[3]);
          $nam_mos_date[$r] = "".$get_md[5]."".$get_md[6]."/".$get_md[8]."".$get_md[9]." @ ".$get_md[11]."".$get_md[12]."z";
          $nam_mos_precip[$r] = "-";
          $nam_mos_sum[$r] = "-";
//          $nam_mos_precip[$r] = $mos[12];
//          $nam_mos_sum[$r] = array_sum($nam_mos_precip);
          $nam_mos_temp[$r] = "".$mos[5]." F";
          $nam_mos_dpt[$r] = "".$mos[6]." F";
          $nam_mos_wind_spd[$r] = "".round($mos[9]*1.15077945,0)." mph";
               $cam_ang = $mos[8];
               if (0 <= $cam_ang && $cam_ang <= 11) {
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }

               elseif (45 < $cam_ang && $cam_ang <= 56) {
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) {
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) {
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }
 
          $nam_mos_wind_dir[$r] = $dir;
     }
}

$mos_year = date('Y',$t_gfs[0]);
$mos_mon = date('m',$t_gfs[0]);
$mos_day = date('d',$t_gfs[0]);
$mos_h = date('H',$t_gfs[0]);

$mos_time = "".$mos_year."-".$mos_mon."-".$mos_day."%20".$mos_h.":00";

$r = -1;
$link5 = "http://mesonet.agron.iastate.edu/mos/csv.php?station=K".$ob_station."&runtime=".$mos_time."&model=GFS";

$data = file($link5) or die('Could not read file!');
foreach ($data as $line) {
     $r++;
     $mos = explode(",",trim($line));
     if($mos[5] == $tmp){

     }
     else{
          $gfs_mos_time[$r] = strtotime($mos[3]);
          $get_md = str_split($mos[3]);
          $gfs_mos_date[$r] = "".$get_md[5]."".$get_md[6]."/".$get_md[8]."".$get_md[9]." @ ".$get_md[11]."".$get_md[12]."z";
          $gfs_mos_precip[$r] = "-";
          $gfs_mos_sum[$r] = "-";
          $gfs_mos_temp[$r] = "".$mos[5]." F";
          $gfs_mos_dpt[$r] = "".$mos[6]." F";
          $gfs_mos_wind_spd[$r] = "".round($mos[9]*1.15077945,0)." mph";
               $cam_ang = $mos[8];
               if (0 <= $cam_ang && $cam_ang <= 11) {
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }

               elseif (45 < $cam_ang && $cam_ang <= 56) {
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) {
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) {
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }
 
          $gfs_mos_wind_dir[$r] = $dir;
     }
}

$mos_year = date('Y',$t_gfsm[0]);
$mos_mon = date('m',$t_gfsm[0]);
$mos_day = date('d',$t_gfsm[0]);
$mos_h = date('H',$t_gfsm[0]);

$mos_time = "".$mos_year."-".$mos_mon."-".$mos_day."%20".$mos_h.":00";

$r = -1;
$link5 = "http://mesonet.agron.iastate.edu/mos/csv.php?station=K".$ob_station."&runtime=".$mos_time."&model=GFS";

$data = file($link5) or die('Could not read file!');
foreach ($data as $line) {
     $r++;
     $mos = explode(",",trim($line));
     if($mos[5] == $tmp){

     }
     else{
          $gfsm_mos_time[$r] = strtotime($mos[3]);
          $get_md = str_split($mos[3]);
          $gfsm_mos_date[$r] = "".$get_md[5]."".$get_md[6]."/".$get_md[8]."".$get_md[9]." @ ".$get_md[11]."".$get_md[12]."z";
          $gfsm_mos_precip[$r] = "-";
          $gfsm_mos_sum[$r] = "-";
          $gfsm_mos_temp[$r] = "".$mos[5]." F";
          $gfsm_mos_dpt[$r] = "".$mos[6]." F";
          $gfsm_mos_wind_spd[$r] = "".round($mos[9]*1.15077945,0)." mph";
               $cam_ang = $mos[8];
               if (0 <= $cam_ang && $cam_ang <= 11) {
                    $dir = "N";
               }

               elseif (11 < $cam_ang && $cam_ang <= 34) {
                    $dir = "NNE";
               }

               elseif (34 < $cam_ang && $cam_ang <= 45) {
                    $dir = "NE";
               }

               elseif (45 < $cam_ang && $cam_ang <= 56) {
                    $dir = "NE";
               }

               elseif (56 < $cam_ang && $cam_ang <= 79) {
                    $dir = "ENE";
               }

               elseif (79 < $cam_ang && $cam_ang <= 101) {
                    $dir = "E";
               }

               elseif (101 < $cam_ang && $cam_ang <= 124) {
                    $dir = "ESE";
               }

               elseif (124 < $cam_ang && $cam_ang <= 135) {
                    $dir = "SE";
               }

               elseif (135 < $cam_ang && $cam_ang <= 146) {
                    $dir = "SE";
               }

               elseif (146 < $cam_ang && $cam_ang <=169) {
                    $dir = "SSE";
               }

               elseif (169 < $cam_ang && $cam_ang <=191) {
                    $dir = "S";
               }

               elseif (191 < $cam_ang && $cam_ang <=214) {
                    $dir = "SSW";
               }

               elseif (214 < $cam_ang && $cam_ang <=225) {
                    $dir = "SW";
               }

               elseif (225 < $cam_ang && $cam_ang <=236) {
                    $dir = "SW";
               }

               elseif (236 < $cam_ang && $cam_ang <=259) {
                    $dir = "WSW";
               }

               elseif (259 < $cam_ang && $cam_ang <=281) {
                    $dir = "W";
               }

               elseif (281 < $cam_ang && $cam_ang <=304) {
                    $dir = "WNW";
               }

               elseif (304 < $cam_ang && $cam_ang <=315) {
                    $dir = "NW";
               }

               elseif (315 < $cam_ang && $cam_ang <= 326) {
                    $dir = "NW";
               }

               elseif (326 < $cam_ang && $cam_ang <= 349) {
                    $dir = "NNW";
               }

               elseif (349 < $cam_ang && $cam_ang <= 360) {
                    $dir = "N";
               }
 
          $gfsm_mos_wind_dir[$r] = $dir;
     }
}


?>


<map id ="precip" name="precip">

<?php 

$ul = 61;
$ur = 41;
$lr = 64;
$ll = 359;
$ul1 = $ul;
$lr1 = $lr;

$i_nam = 0;
$i_namm = 0;
$i_gfs = 0;
$i_gfsm = 0;
$i_nam_mos = 1;
$i_gfs_mos = 1;
$i_gfsm_mos = 1;
$i_nws = 0;
$i_obs = 0;

$trip_nam = 0;
$trip_namm = 0;
$trip_gfs = 0;
$trip_gfs2 = 0;
$trip_gfsm = 0;  
$trip_gfsm2 = 0;
$trip_nam_mos = 0;
$trip_nam_mos2 = 0;
$trip_gfs_mos = 0;
$trip_gfs_mos2 = 0;
$trip_gfsm_mos = 0;
$trip_gfsm_mos2 = 0;
$trip_nws = 0;
$trip_nws2 = 0;
$trip_obs = 0;

$gfs_check_time = $t_gfs[0];
$gfsm_check_time = $t_gfsm[0];
$nam_mos_check_time = $t[6];
$gfs_mos_check_time = $t_gfs[2];
$gfsm_mos_check_time = $t_gfsm[2];
$nws_check_time = $nws_time_1[0];

//$min = min($t[0],$t_namm[0],$t_gfs[0],$t_gfsm[0]);
//$max = max($t[$v],$t_namm[$a],$t_gfs[$b],$t_gfsm[$c]);

$cur_time = $min;
$add_time = ($max - $min)/ 3600;
$model_count = $add_time;
//echo "".$t[0].",".$min."";
//die();
for ($num = 0; $num <= $model_count; $num++) {

     $hr = $num + 1;

     if($min+3600 == $cur_time){
          $trip_obs = 1;
     }
     if($nws_time_1[0] == $cur_time){
          $trip_nws = 1;
          $trip_nws2 = 1;
     }
     if($nws_check_time == $cur_time){
          $trip_nws = 1;
          $trip_nws2 = 1;
     }
     if($i_nws > $lf){
          $trip_nws2 = 0;
     }

     if($t[0] == $cur_time){
          $trip_nam = 1;
     }
     if($t[6] == $cur_time){
          $trip_nam_mos = 1;
          $trip_nam_mos2 = 1;
     }
     if($nam_mos_check_time == $cur_time){
          $trip_nam_mos = 1;
          $trip_nam_mos2 = 1;
     }
     if($i_nam_mos > 21){
          $trip_nam_mos2 = 0;
     }
     if($t_namm[0] == $cur_time){
          $trip_namm = 1;
     }

     if($t_gfs[2] == $cur_time){
          $trip_gfs_mos = 1;
          $trip_gfs_mos2 = 1;
     }
     if($gfs_mos_check_time == $cur_time){
          $trip_gfs_mos = 1;
          $trip_gfs_mos2 = 1;
     }
     if($i_gfs_mos > 21){
          $trip_gfs_mos2 = 0;
     }

     if($t_gfsm[2] == $cur_time){
          $trip_gfsm_mos = 1;
          $trip_gfsm_mos2 = 1;
     }
     if($gfsm_mos_check_time == $cur_time){
          $trip_gfsm_mos = 1;
          $trip_gfsm_mos2 = 1;
     }
     if($i_gfsm_mos > 21){
          $trip_gfsm_mos2 = 0;
     }

     if($gfs_check_time == $cur_time){
          $trip_gfs = 1;
          $trip_gfs2 = 1;
     }
     if($i_gfs > 60){
          $trip_gfs2 = 0;
     }    
     if($gfsm_check_time == $cur_time){
          $trip_gfsm = 1;
          $trip_gfsm2 = 1;
     }
     if($i_gfsm > 60){
          $trip_gfsm2 = 0;
     }


     $string_begin = "<area shape =\"rect\" coords =\"".$ul.",".$ur.",".$lr.",".$ll."\"onMouseOver=\"writeText('<tr>";
     $string_end = "</tr>')\"/>\n";

     if($trip_nam == 0 || $i_nam > 84){
          $string_nam = "<td width=86><font color=000000>".$hr_nam_init."z NAM<br></td>";
     }
     if($trip_nam == 1 && $i_nam <= 84){
          $string_nam1 = "<td width=86 border=1><font color=000000>".$hr_nam_init."z NAM<br>";
          $string_nam2 = "".$date[$i_nam]."</font><br>";
          $string_nam3 = "<font color=0000FF>".$precip[$i_nam]."</font><br>";
          $string_nam4 = "<font color=000099>".$sum[$i_nam]."</font><br>";
          $string_nam5 = "<font color=CC0000>".$temp[$i_nam]."</font><br>";
          $string_nam6 = "<font color=006600>".$dew[$i_nam]."</font><br>";
          $string_nam7 = "<font color=000000>".$wind_10m[$i_nam]."</font><br>";
          $string_nam8 = "<font color=000000>".$met_dir[$i_nam]."</font></td>";
          $string_nam = "".$string_nam1."".$string_nam2."".$string_nam3."".$string_nam4."".$string_nam5."".$string_nam6."".$string_nam7."".$string_nam8."";  
          $i_nam++;
     }
     if($trip_namm == 0 || $i_namm > 84){
          $string_namm = "<td width=86><font color=000000>".$hr_namm_init."z NAM<br></td>";
     }
     if($trip_namm == 1 && $i_namm <= 84){
          $string_namm1 = "<td width=86><font color=000000>".$hr_namm_init."z NAM<br>";
          $string_namm2 = "".$date_namm[$i_namm]."</font><br>";
          $string_namm3 = "<font color=0000FF>".$precip_namm[$i_namm]."</font><br>";
          $string_namm4 = "<font color=000099>".$sum_namm[$i_namm]."</font><br>";
          $string_namm5 = "<font color=CC0000>".$temp_namm[$i_namm]."</font><br>";
          $string_namm6 = "<font color=006600>".$dew_namm[$i_namm]."</font><br>";
          $string_namm7 = "<font color=000000>".$wind_10m_namm[$i_namm]."</font>";
          $string_namm8 = "<br><font color=000000>".$met_dir_namm[$i_namm]."</font></td>";
          $string_namm = "".$string_namm1."".$string_namm2."".$string_namm3."".$string_namm4."".$string_namm5."".$string_namm6."".$string_namm7."".$string_namm8."";  
          $i_namm++;
     }
     if($trip_gfs == 0){
          if($trip_gfs2 == 0){
               $string_gfs = "<td width=86><font color=000000>".$hr_gfs_init."z GFS<br></td>";
          }
          if($trip_gfs2 == 1 && $i_gfs <= 60){
               $string_gfs1 = "<td width=86><font color=000000>".$hr_gfs_init."z GFS<br>";
               $string_gfs2 = "".$date_gfs[$i_gfs]."</font><br><font color=0000FF>".$precip_gfs[$i_gfs]."</font><br>";
               $string_gfs3 = "<font color=000099>".$sum_gfs[$i_gfs]."</font><br><font color=CC0000>".$temp_gfs[$i_gfs]."</font><br>";
               $string_gfs4 = "<font color=006600>".$dew_gfs[$i_gfs]."</font><br>";
               $string_gfs5 = "<font color=000000>".$wind_10m_gfs[$i_gfs]."</font><br>";
               $string_gfs6 = "<font color=000000>".$met_dir_gfs[$i_gfs]."</font></td>";
               $string_gfs = "".$string_gfs1."".$string_gfs2."".$string_gfs3."".$string_gfs4."".$string_gfs5."".$string_gfs6."";
          }
     }

     if($trip_gfs == 1 && $i_gfs <= 60){
          $string_gfs1 = "<td  width=86><font color=000000>".$hr_gfs_init."z GFS<br>";
          $string_gfs2 = "".$date_gfs[$i_gfs]."</font><br><font color=0000FF>".$precip_gfs[$i_gfs]."</font><br>";
          $string_gfs3 = "<font color=000099>".$sum_gfs[$i_gfs]."</font><br><font color=CC0000>".$temp_gfs[$i_gfs]."</font><br>";
          $string_gfs4 = "<font color=006600>".$dew_gfs[$i_gfs]."</font><br>";
          $string_gfs5 = "<font color=000000>".$wind_10m_gfs[$i_gfs]."</font><br>";
          $string_gfs6 = "<font color=000000>".$met_dir_gfs[$i_gfs]."</font></td>";
          $string_gfs = "".$string_gfs1."".$string_gfs2."".$string_gfs3."".$string_gfs4."".$string_gfs5."".$string_gfs6.""; 
          $i_gfs++;
          $gfs_check_time = $gfs_check_time + 10800;
          $trip_gfs = 0;
     }  

     if($trip_gfsm == 0){
          if($trip_gfsm2 == 0){
               $string_gfsm = "<td width=86><font color=000000>".$hr_gfsm_init."z GFS<br></td>";
          }
          if($trip_gfsm2 == 1 && $i_gfsm <= 60){
               $string_gfsm1 = "<td width=86><font color=000000>".$hr_gfsm_init."z GFS<br>";
               $string_gfsm2 = "".$date_gfsm[$i_gfsm]."</font><br><font color=0000FF>".$precip_gfsm[$i_gfsm]."</font><br>";
               $string_gfsm3 = "<font color=000099>".$sum_gfsm[$i_gfsm]."</font><br><font color=CC0000>".$temp_gfsm[$i_gfsm]."</font><br>";
               $string_gfsm4 = "<font color=006600>".$dew_gfsm[$i_gfsm]."</font><br>";
               $string_gfsm5 = "<font color=000000>".$wind_10m_gfsm[$i_gfsm]."</font><br>";
               $string_gfsm6 = "<font color=000000>".$met_dir_gfsm[$i_gfsm]."</font></td>";
               $string_gfsm = "".$string_gfsm1."".$string_gfsm2."".$string_gfsm3."".$string_gfsm4."".$string_gfsm5."".$string_gfsm6."";
          }
     }

     if($trip_gfsm == 1 && $i_gfsm <= 60){
          $string_gfsm1 = "<td width=86><font color=000000>".$hr_gfsm_init."z GFS<br>";
          $string_gfsm2 = "".$date_gfsm[$i_gfsm]."</font><br><font color=0000FF>".$precip_gfsm[$i_gfsm]."</font><br>";
          $string_gfsm3 = "<font color=000099>".$sum_gfsm[$i_gfsm]."</font><br><font color=CC0000>".$temp_gfsm[$i_gfsm]."</font><br>";
          $string_gfsm4 = "<font color=006600>".$dew_gfsm[$i_gfsm]."</font><br>";
          $string_gfsm5 = "<font color=000000>".$wind_10m_gfsm[$i_gfsm]."</font><br>"; 
          $string_gfsm6 = "<font color=000000>".$met_dir_gfsm[$i_gfsm]."</font></td>";
          $string_gfsm = "".$string_gfsm1."".$string_gfsm2."".$string_gfsm3."".$string_gfsm4."".$string_gfsm5."".$string_gfsm6."";
          $i_gfsm++;
          $gfsm_check_time = $gfsm_check_time + 10800;
          $trip_gfsm = 0;
     }

     if($trip_nam_mos == 0 || $i_nam_mos > 21){
          if($trip_nam_mos2 == 0){
               $string_nam_mos = "<td width=86><font color=000000>".$hr_nam_init."z NAM MOS<br></td>";
          }
          if($trip_nam_mos2 == 1 && $i_nam_mos <= 21){
               $string_nam_mos1 = "<td width=86><font color=000000>".$hr_nam_init."z NAM MOS<br>";
               $string_nam_mos2 = "".$nam_mos_date[$i_nam_mos]."</font><br><font color=0000FF>".$nam_mos_precip[$i_nam_mos]."</font><br>";
               $string_nam_mos3 = "<font color=000099>".$nam_mos_sum[$i_nam_mos]."</font><br><font color=CC0000>".$nam_mos_temp[$i_nam_mos]."</font><br>";
               $string_nam_mos4 = "<font color=006600>".$nam_mos_dpt[$i_nam_mos]."</font><br>";
               $string_nam_mos5 = "<font color=000000>".$nam_mos_wind_spd[$i_nam_mos]."</font><br>";
               $string_nam_mos6 = "<font color=000000>".$nam_mos_wind_dir[$i_nam_mos]."</font></td>";
               $string_nam_mos = "".$string_nam_mos1."".$string_nam_mos2."".$string_nam_mos3."".$string_nam_mos4."".$string_nam_mos5."".$string_nam_mos6."";
          }
     }
     if($trip_nam_mos == 1 && $i_nam_mos <= 21){
          $string_nam_mos1 = "<td width=86><font color=000000>".$hr_nam_init."z NAM MOS<br>";
          $string_nam_mos2 = "".$nam_mos_date[$i_nam_mos]."</font><br>";
          $string_nam_mos3 = "<font color=0000FF>".$nam_mos_precip[$i_nam_mos]."</font><br>";
          $string_nam_mos4 = "<font color=000099>".$nam_mos_sum[$i_nam_mos]."</font><br>";
          $string_nam_mos5 = "<font color=CC0000>".$nam_mos_temp[$i_nam_mos]."</font><br>";
          $string_nam_mos6 = "<font color=006600>".$nam_mos_dpt[$i_nam_mos]."</font><br>";
          $string_nam_mos7 = "<font color=000000>".$nam_mos_wind_spd[$i_nam_mos]."</font><br>";
          $string_nam_mos8 = "<font color=000000>".$nam_mos_wind_dir[$i_nam_mos]."</font></td>";
          $string_nam_mos = "".$string_nam_mos1."".$string_nam_mos2."".$string_nam_mos3."".$string_nam_mos4."".$string_nam_mos5."".$string_nam_mos6."".$string_nam_mos7."".$string_nam_mos8."";
          $i_nam_mos++;
          $nam_mos_check_time = $nam_mos_check_time + 10800;
          if($i_nam_mos >= 20){
               $nam_mos_check_time = $nam_mos_check_time + 10800;
          }
          $trip_nam_mos = 0;
     }

     if($trip_gfs_mos == 0 || $i_gfs_mos > 21){
          if($trip_gfs_mos2 == 0){
               $string_gfs_mos = "<td width=86><font color=000000>".$hr_gfs_init."z GFS MOS<br></td>";
          }
          if($trip_gfs_mos2 == 1 && $i_gfs_mos <= 21){
               $string_gfs_mos1 = "<td width=86><font color=000000>".$hr_gfs_init."z GFS MOS<br>";
               $string_gfs_mos2 = "".$gfs_mos_date[$i_gfs_mos]."</font><br><font color=0000FF>".$gfs_mos_precip[$i_gfs_mos]."</font><br>";
               $string_gfs_mos3 = "<font color=000099>".$gfs_mos_sum[$i_gfs_mos]."</font><br><font color=CC0000>".$gfs_mos_temp[$i_gfs_mos]."</font><br>";
               $string_gfs_mos4 = "<font color=006600>".$gfs_mos_dpt[$i_gfs_mos]."</font><br>";
               $string_gfs_mos5 = "<font color=000000>".$gfs_mos_wind_spd[$i_gfs_mos]."</font><br>";
               $string_gfs_mos6 = "<font color=000000>".$gfs_mos_wind_dir[$i_gfs_mos]."</font></td>";
               $string_gfs_mos = "".$string_gfs_mos1."".$string_gfs_mos2."".$string_gfs_mos3."".$string_gfs_mos4."".$string_gfs_mos5."".$string_gfs_mos6."";
          }
     }
     if($trip_gfs_mos == 1 && $i_gfs_mos <= 21){
          $string_gfs_mos1 = "<td width=86><font color=000000>".$hr_gfs_init."z GFS MOS<br>";
          $string_gfs_mos2 = "".$gfs_mos_date[$i_gfs_mos]."</font><br>";
          $string_gfs_mos3 = "<font color=0000FF>".$gfs_mos_precip[$i_gfs_mos]."</font><br>";
          $string_gfs_mos4 = "<font color=000099>".$gfs_mos_sum[$i_gfs_mos]."</font><br>";
          $string_gfs_mos5 = "<font color=CC0000>".$gfs_mos_temp[$i_gfs_mos]."</font><br>";
          $string_gfs_mos6 = "<font color=006600>".$gfs_mos_dpt[$i_gfs_mos]."</font><br>";
          $string_gfs_mos7 = "<font color=000000>".$gfs_mos_wind_spd[$i_gfs_mos]."</font><br>";
          $string_gfs_mos8 = "<font color=000000>".$gfs_mos_wind_dir[$i_gfs_mos]."</font></td>";
          $string_gfs_mos = "".$string_gfs_mos1."".$string_gfs_mos2."".$string_gfs_mos3."".$string_gfs_mos4."".$string_gfs_mos5."".$string_gfs_mos6."".$string_gfs_mos7."".$string_gfs_mos8."";
          $i_gfs_mos++;
          $gfs_mos_check_time = $gfs_mos_check_time + 10800;
          if($i_gfs_mos >= 20){
               $gfs_mos_check_time = $gfs_mos_check_time + 10800;
          }
          $trip_gfs_mos = 0;
     }

     if($trip_gfsm_mos == 0 || $i_gfsm_mos > 21){
          if($trip_gfsm_mos2 == 0){
               $string_gfsm_mos = "<td width=86><font color=000000>".$hr_gfsm_init."z GFS MOS<br></td>";
          }
          if($trip_gfsm_mos2 == 1 && $i_gfsm_mos <= 21){
               $string_gfsm_mos1 = "<td width=86><font color=000000>".$hr_gfsm_init."z GFS MOS<br>";
               $string_gfsm_mos2 = "".$gfsm_mos_date[$i_gfsm_mos]."</font><br><font color=0000FF>".$gfsm_mos_precip[$i_gfsm_mos]."</font><br>";
               $string_gfsm_mos3 = "<font color=000099>".$gfsm_mos_sum[$i_gfsm_mos]."</font><br><font color=CC0000>".$gfsm_mos_temp[$i_gfsm_mos]."</font><br>";
               $string_gfsm_mos4 = "<font color=006600>".$gfsm_mos_dpt[$i_gfsm_mos]."</font><br>";
               $string_gfsm_mos5 = "<font color=000000>".$gfsm_mos_wind_spd[$i_gfsm_mos]."</font><br>";
               $string_gfsm_mos6 = "<font color=000000>".$gfsm_mos_wind_dir[$i_gfsm_mos]."</font></td>";
               $string_gfsm_mos = "".$string_gfsm_mos1."".$string_gfsm_mos2."".$string_gfsm_mos3."".$string_gfsm_mos4."".$string_gfsm_mos5."".$string_gfsm_mos6."";
          }
     }
     if($trip_gfsm_mos == 1 && $i_gfsm_mos <= 21){
          $string_gfsm_mos1 = "<td width=86><font color=000000>".$hr_gfsm_init."z GFS MOS<br>";
          $string_gfsm_mos2 = "".$gfsm_mos_date[$i_gfsm_mos]."</font><br>";
          $string_gfsm_mos3 = "<font color=0000FF>".$gfsm_mos_precip[$i_gfsm_mos]."</font><br>";
          $string_gfsm_mos4 = "<font color=000099>".$gfsm_mos_sum[$i_gfsm_mos]."</font><br>";
          $string_gfsm_mos5 = "<font color=CC0000>".$gfsm_mos_temp[$i_gfsm_mos]."</font><br>";
          $string_gfsm_mos6 = "<font color=006600>".$gfsm_mos_dpt[$i_gfsm_mos]."</font><br>";
          $string_gfsm_mos7 = "<font color=000000>".$gfsm_mos_wind_spd[$i_gfsm_mos]."</font><br>";
          $string_gfsm_mos8 = "<font color=000000>".$gfsm_mos_wind_dir[$i_gfsm_mos]."</font></td>";
          $string_gfsm_mos = "".$string_gfsm_mos1."".$string_gfsm_mos2."".$string_gfsm_mos3."".$string_gfsm_mos4."".$string_gfsm_mos5."".$string_gfsm_mos6."".$string_gfsm_mos7."".$string_gfsm_mos8."";
          $i_gfsm_mos++;
          $gfsm_mos_check_time = $gfsm_mos_check_time + 10800;
          if($i_gfsm_mos >= 20){
               $gfsm_mos_check_time = $gfsm_mos_check_time + 10800;
          }
          $trip_gfsm_mos = 0;
     }

     if($trip_nws == 0 || $i_nws > $lf){
          if($trip_nws2 == 0){
               $string_nws = "<td width=86><font color=000000>NWS<br></td>";
          }
          if($trip_nws2 == 1 && $i_nws <= $lf){
               $string_nws1 = "<td width=86><font color=000000>NWS<br>";
               $string_nws2 = "".$nws_date[$i_nws]."</font><br><font color=0000FF>".$nws_precip[$i_nws]."</font><br>";
               $string_nws3 = "<font color=000099>".$nws_sum[$i_nws]."</font><br><font color=CC0000>".$nws_temp[$i_nws]."</font><br>";
               $string_nws4 = "<font color=006600>".$nws_dpt[$i_nws]."</font><br>";
               $string_nws5 = "<font color=000000>".$nws_wind_spd[$i_nws]."</font><br>";
               $string_nws6 = "<font color=000000>".$nws_wind_dir[$i_nws]."</font></td>";
               $string_nws = "".$string_nws1."".$string_nws2."".$string_nws3."".$string_nws4."".$string_nws5."".$string_nws6."";
          }
     }
     if($trip_nws == 1 && $i_nws <= $lf){
          $string_nws1 = "<td width=86><font color=000000>NWS<br>";
          $string_nws2 = "".$nws_date[$i_nws]."</font><br>";
          $string_nws3 = "<font color=0000FF>".$nws_precip[$i_nws]."</font><br>";
          $string_nws4 = "<font color=000099>".$nws_sum[$i_nws]."</font><br>";
          $string_nws5 = "<font color=CC0000>".$nws_temp[$i_nws]."</font><br>";
          $string_nws6 = "<font color=006600>".$nws_dpt[$i_nws]."</font><br>";
          $string_nws7 = "<font color=000000>".$nws_wind_spd[$i_nws]."</font><br>";
          $string_nws8 = "<font color=000000>".$nws_wind_dir[$i_nws]."</font></td>";
          $string_nws = "".$string_nws1."".$string_nws2."".$string_nws3."".$string_nws4."".$string_nws5."".$string_nws6."".$string_nws7."".$string_nws8."";
          $i_nws++;
          $nws_check_time = $nws_check_time + 10800;
          if($i_nws >= $nws_int){
               $nws_check_time = $nws_check_time + 10800;
          }
          $trip_nws = 0;
     }

     if($trip_obs == 0 || $i_obs > $kf){
          $string_obs = "<td width=86><font color=000000>OBS - K".$ob_station."<br></td>";
     }
     if($trip_obs == 1 && $i_obs <= $kf){
          $string_obs1 = "<td width=86><font color=000000>OBS - K".$ob_station."<br>";
          $string_obs2 = "".$obs_date[$i_obs]."</font><br>";
          $string_obs3 = "<font color=0000FF>".$obs_precip[$i_obs]."</font><br>";
          $string_obs4 = "<font color=000099>".$obs_sum[$i_obs]."</font><br>";
          $string_obs5 = "<font color=CC0000>".$obs_temp[$i_obs]."</font><br>";
          $string_obs6 = "<font color=006600>".$obs_dpt[$i_obs]."</font><br>";
          $string_obs7 = "<font color=000000>".$obs_wind_spd[$i_obs]."</font><br>";
          $string_obs8 = "<font color=000000>".$obs_wind_dir[$i_obs]."</font></td>";
          $string_obs = "".$string_obs1."".$string_obs2."".$string_obs3."".$string_obs4."".$string_obs5."".$string_obs6."".$string_obs7."".$string_obs8."";
          $i_obs++;
     }

     echo "".$string_begin."".$string_nam."".$string_namm."".$string_gfs."".$string_gfsm."".$string_nam_mos."".$string_gfs_mos."".$string_gfsm_mos."".$string_nws."".$string_obs."".$string_end."";

     $ul1 = $ul1+(899/($model_count+1));
     $lr1 = $lr1+(899/($model_count+1));

     $ul = round(($ul1),0);
     $lr = round(($lr1),0);

     $cur_time = $cur_time + 3600;

}

?>

</map>

<script type="text/javascript">
var sc_project=5230524; 
var sc_invisible=1; 
var sc_partition=59; 
var sc_click_stat=1; 
var sc_security="5b0b2ca6"; 
</script>

<script type="text/javascript"
src="http://www.statcounter.com/counter/counter.js"></script><noscript><div
class="statcounter"><a title="wordpress blog stats"
href="http://www.statcounter.com/wordpress.com/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/5230524/0/5b0b2ca6/1/"
alt="wordpress blog stats" ></a></div></noscript>

</body>
</html>


